test: add job-retries

diff --git a/.github/workflows/test_backend.yml b/.github/workflows/test_backend.yml
--- a/.github/workflows/test_backend.yml
+++ b/.github/workflows/test_backend.yml
@@ -121,6 +121,21 @@ jobs:
         run: |
           rm -rf src/oxl_ansible_webui/aw/migrations/*
           cp /tmp/migrations/* src/oxl_ansible_webui/aw/migrations/
-          bash scripts/test_api.sh
+
+          set +e
+          for i in {1..3}
+          do
+            if (( i > 1 ))
+            then
+              echo "### RETRY $(( i - 1 )) ###"
+            fi
+
+            bash scripts/test_api.sh
+            if [[ "$?" == "0" ]]
+            then
+              exit 0
+            fi
+          done
+          exit 1
         env:
           PYTHONUNBUFFERED: 1
diff --git a/.github/workflows/test_dbs.yml b/.github/workflows/test_dbs.yml
--- a/.github/workflows/test_dbs.yml
+++ b/.github/workflows/test_dbs.yml
@@ -62,7 +62,22 @@ jobs:
           pip install -r requirements_test_backend.txt >/dev/null
 
       - name: Testing SQLite
-        run: bash scripts/test_db_sqlite.sh
+        run: |
+          set +e
+          for i in {1..3}
+          do
+            if (( i > 1 ))
+            then
+              echo "### RETRY $(( i - 1 )) ###"
+            fi
+
+            bash scripts/test_db_sqlite.sh
+            if [[ "$?" == "0" ]]
+            then
+              exit 0
+            fi
+          done
+          exit 1
         env:
           PYTHONUNBUFFERED: 1
 
@@ -72,7 +87,22 @@ jobs:
           pip install mysqlclient >/dev/null
 
       - name: Testing MariaDB/MySQL
-        run: bash scripts/test_db_mariadb.sh
+        run: |
+          set +e
+          for i in {1..3}
+          do
+            if (( i > 1 ))
+            then
+              echo "### RETRY $(( i - 1 )) ###"
+            fi
+
+            bash scripts/test_db_mariadb.sh
+            if [[ "$?" == "0" ]]
+            then
+              exit 0
+            fi
+          done
+          exit 1
         env:
           PYTHONUNBUFFERED: 1
 
@@ -81,6 +111,21 @@ jobs:
           pip install psycopg[binary,pool] >/dev/null
 
       - name: Testing PostgreSQL
-        run: bash scripts/test_db_psql.sh
+        run: |
+          set +e
+          for i in {1..3}
+          do
+            if (( i > 1 ))
+            then
+              echo "### RETRY $(( i - 1 )) ###"
+            fi
+
+            bash scripts/test_db_psql.sh
+            if [[ "$?" == "0" ]]
+            then
+              exit 0
+            fi
+          done
+          exit 1
         env:
           PYTHONUNBUFFERED: 1
diff --git a/.github/workflows/test_job_execution.yml b/.github/workflows/test_job_execution.yml
--- a/.github/workflows/test_job_execution.yml
+++ b/.github/workflows/test_job_execution.yml
@@ -49,6 +49,21 @@ jobs:
           pip install -r requirements_test_backend.txt >/dev/null
 
       - name: Running Job-Execution Integration Tests
-        run: bash scripts/test_job_exec.sh
+        run: |
+          set +e
+          for i in {1..3}
+          do
+            if (( i > 1 ))
+            then
+              echo "### RETRY $(( i - 1 )) ###"
+            fi
+
+            bash scripts/test_job_exec.sh
+            if [[ "$?" == "0" ]]
+            then
+              exit 0
+            fi
+          done
+          exit 1
         env:
           PYTHONUNBUFFERED: 1
